spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Account
      database: Account
  application:
    name: AccountService
server:
  port: 9004
  servlet:
    context-path: /api/account
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true