spring:
  application:
    name: NotificationService
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable:true
server:
  port: 9005
  servlet:
    context-path: /api/notify
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true