spring:
  application:
    name: NotificationService
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable:true
server:
  port: 9005
  servlet:
    context-path: /api/notify
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true