spring:
  application:
    name: PaymentProcessing
server:
  port: 9007
  servlet:
    context-path: /api/process
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
