FROM maven:3.8.3-openjdk-17
WORKDIR /AccountServiceDir
COPY ./AccountService/pom.xml .
COPY ./AccountService/src ./src
RUN mvn clean package -DskipTests
EXPOSE 9000
CMD [ "java","-jar", "target/AccountService-0.0.1-SNAPSHOT.jar"]