FROM maven:3.8.3-openjdk-17
WORKDIR /AuthServiceDir
COPY ./AuthenticationService/pom.xml .
COPY ./AuthenticationService/src ./src
RUN mvn clean package -DskipTests
EXPOSE 9001
CMD [ "java","-jar", "target/AuthenticationService-0.1-SNAPSHOT.jar"]